package rules;

import org.yuenio.droolSandbox.model.Email;

dialect  "mvel"

rule "Team A"
    when
        EmailObject : Email(subject == "Team AMY");
    then
        System.out.println("assign to Team AMY");
        EmailObject.setTeamAssigned("Team_AMY");
end;

rule "Team B"
    when
        EmailObject : Email(subject == "Team BOB");
    then
        System.out.println("assign to Team BOB");
        EmailObject.setTeamAssigned("Team_BOB");
end;
