package rules;

import org.yuenio.droolSandbox.model.Email;

dialect  "mvel"

rule "Team A"
    when
        EmailObject : Email(subject == "Team A");
    then
        System.out.println("assign to Team A");
        EmailObject.setTeamAssigned("Team A");
end;

rule "Team B"
    when
        EmailObject : Email(subject == "Team BOB");
    then
        System.out.println("assign to Team BOB");
        EmailObject.setTeamAssigned("Team_BOB");
end;
